### ISSUE TITLE
Handling comments

### ISSUE THREAD

**Issue by samrjenkins** [samrjenkins/yalphabetize#1]
Yalphabetize does not currently preserve comments when reordering a YAML file.

Ruby's Psych parser does not parse comments into the AST.

I have been unable to figure out a reliable way of knowing where a comment should be reinserted into the YAML file after alphabetisation. For example:
ORIGINAL CODE
```yaml
# A comment
Bananas: 2
Apples: 1
```
POSSIBLE OPTIONS AFTER ALPHABETISATION
```yaml
# Sometimes the comment might belong at the top of the file
Apples: 1
Bananas: 2
```
```yaml
Apples: 1
# Sometimes the comment is coupled to the line of code beneath it
Bananas: 2
```
