### ISSUE TITLE
case sensitive/insensitive option

### ISSUE THREAD

**Issue by samrjenkins** [samrjenkins/yalphabetize#14]
We should be able to alphabetise with case sensitivity
```yml
A: 1
B: 2
a: 3
b: 4
```
or case insensitivity
```yml
A: 1
a: 3
B: 2
b: 4
```
