### ISSUE TITLE
Handle sequence indentation

### ISSUE THREAD

**Issue by samrjenkins** [samrjenkins/yalphabetize#42]
Autocorrecting a file with a sequence nested within a mapping
```yml
mapping:
  - element1
  - element2
another_key: another_value
```
does not preserve the original indentation of the array.

Actual:
```yml
another_key: another_value
mapping:
- element1
- element2
```
Expected:
```yml
another_key: another_value
mapping:
  - element1
  - element2
```
