### ISSUE TITLE
Environment variables inside arrays

### ISSUE THREAD

**Issue by samrjenkins** [samrjenkins/yalphabetize#6]
```yml
:concurrency: 1
:queues:
  - scheduler
tasks: &tasks
  Dsp::UpdateUnavailableItemsEnqueuer:
    every: [ <%= ENV.fetch("FREQUENCY_HIDE_UNAVAILABLE_ITEMS_WORKER") { "1m" } %> ]
    queue: default
```
