### ISSUE TITLE
Advanced custom ordering

### ISSUE THREAD

**Issue by samrjenkins** [samrjenkins/yalphabetize#79]
Allow for custom ordering, for example numerical:
```yml
one: 1,
two: 2,
three: 3,
four: 4
```
